// src/components/GitHubConfig.tsx
'use client';

import { useState, useEffect } from 'react';

interface GitHubRepo {
  repository: string;
  token: string;
  branch: string;
}

interface GitHubConfigProps {
  onConfigChange?: (config: GitHubRepo | null) => void;
  className?: string;
}

export function GitHubConfig({ onConfigChange, className = '' }: GitHubConfigProps) {
  const [config, setConfig] = useState<GitHubRepo>({
    repository: '',
    token: '',
    branch: 'main'
  });
  const [isOpen, setIsOpen] = useState(false);
  const [isConnected, setIsConnected] = useState(false);
  const [branches, setBranches] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [showCreateBranch, setShowCreateBranch] = useState(false);
  const [newBranchName, setNewBranchName] = useState('');
  const [sourceBranch, setSourceBranch] = useState('');

  // Load saved config on mount
  useEffect(() => {
    const saved = localStorage.getItem('github-config');
    if (saved) {
      const savedConfig = JSON.parse(saved);
      setConfig(savedConfig);
      setIsConnected(!!savedConfig.repository && !!savedConfig.token);
      if (onConfigChange) {
        onConfigChange(savedConfig);
      }
    }
  }, [onConfigChange]);

  const handleSave = async () => {
    if (!config.repository || !config.token) {
      alert('Please enter repository name and GitHub token');
      return;
    }

    // Clean and validate repository name
    let repoName = config.repository.trim();

    // Remove GitHub URL if user entered the full URL
    if (repoName.startsWith('https://github.com/')) {
      repoName = repoName.replace('https://github.com/', '');
    } else if (repoName.startsWith('github.com/')) {
      repoName = repoName.replace('github.com/', '');
    }

    // Validate format (username/repository)
    if (!repoName.includes('/') || repoName.split('/').length !== 2) {
      alert('Repository name must be in the format "username/repository-name"\n\nExample: "john/my-tokens" or "company/design-system"');
      return;
    }

    // Update config with cleaned repository name
    const cleanedConfig = { ...config, repository: repoName };
    setConfig(cleanedConfig);

    setLoading(true);
    try {
      // Test connection and fetch branches using our API
      const response = await fetch(`/api/github/branches?repository=${encodeURIComponent(repoName)}&githubToken=${encodeURIComponent(config.token)}`);

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Failed to connect to repository '${repoName}'. Check repository name and token permissions.`);
      }

      const result = await response.json();
      const branchNames = result.branches.map((branch: any) => branch.name);
      setBranches(branchNames);

      // If current branch doesn't exist in repo, default to main or first available
      if (!branchNames.includes(cleanedConfig.branch)) {
        const defaultBranch = branchNames.includes('main') ? 'main' : branchNames[0] || 'main';
        cleanedConfig.branch = defaultBranch;
        setConfig({ ...cleanedConfig, branch: defaultBranch });
      }

      localStorage.setItem('github-config', JSON.stringify(cleanedConfig));
      setIsConnected(true);
      setIsOpen(false);

      if (onConfigChange) {
        onConfigChange(cleanedConfig);
      }
    } catch (error) {
      console.error('GitHub connection error:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';

      // Provide more helpful error messages
      let friendlyMessage = errorMessage;
      if (errorMessage.includes('404') || errorMessage.includes('Not Found')) {
        friendlyMessage = `Repository '${config.repository}' not found. Please check the repository name and ensure it exists.`;
      } else if (errorMessage.includes('401') || errorMessage.includes('403')) {
        friendlyMessage = `Access denied to repository '${config.repository}'. Please check your token permissions.`;
      } else if (errorMessage.includes('Failed to fetch')) {
        friendlyMessage = `Network error. Please check your internet connection and try again.`;
      }

      alert(`Connection failed: ${friendlyMessage}`);
    } finally {
      setLoading(false);
    }
  };

  const handleDisconnect = () => {
    if (confirm('Are you sure you want to reset your GitHub connection? This will clear all saved settings including your token.')) {
      localStorage.removeItem('github-config');
      setConfig({ repository: '', token: '', branch: 'main' });
      setIsConnected(false);
      setBranches([]);
      setIsOpen(false); // Close the dialog after disconnect
      if (onConfigChange) {
        onConfigChange(null);
      }
      alert('GitHub connection reset successfully. You can now configure a new connection.');
    }
  };

  const handleCreateBranch = async () => {
    if (!newBranchName.trim()) {
      alert('Please enter a branch name');
      return;
    }

    if (!sourceBranch) {
      alert('Please select a source branch');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch('/api/github/branches', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repository: config.repository,
          githubToken: config.token,
          branchName: newBranchName.trim(),
          sourceBranch: sourceBranch
        }),
      });

      const result = await response.json();
      if (response.ok) {
        // Refresh branches list
        const branchesResponse = await fetch(`/api/github/branches?repository=${encodeURIComponent(config.repository)}&githubToken=${encodeURIComponent(config.token)}`);

        if (branchesResponse.ok) {
          const result = await branchesResponse.json();
          const branchNames = result.branches.map((branch: any) => branch.name);
          setBranches(branchNames);
        }

        // Switch to the new branch
        const updatedConfig = { ...config, branch: newBranchName.trim() };
        setConfig(updatedConfig);
        localStorage.setItem('github-config', JSON.stringify(updatedConfig));
        if (onConfigChange) {
          onConfigChange(updatedConfig);
        }

        setShowCreateBranch(false);
        setNewBranchName('');
        setSourceBranch('');
        alert(result.message);
      } else {
        alert(`Failed to create branch: ${result.error}`);
      }
    } catch (error) {
      alert(`Error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={className}>
      <div className="flex items-center gap-2">
        <button
          onClick={() => setIsOpen(true)}
          className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
            isConnected
              ? 'bg-green-100 text-green-800 hover:bg-green-200'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
          }`}
        >
          {isConnected ? (
            <span className="flex items-center gap-2">
              <span className="w-2 h-2 bg-green-500 rounded-full"></span>
              {config.repository} ({config.branch})
            </span>
          ) : (
            'Configure GitHub'
          )}
        </button>

        {isConnected && (
          <button
            onClick={() => setIsOpen(true)}
            className="px-2 py-1 text-xs bg-blue-100 text-blue-700 hover:bg-blue-200 rounded transition-colors"
            title="Reconfigure GitHub connection (e.g., update token)"
          >
            Reconfigure
          </button>
        )}
      </div>

      {isOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <div className="flex justify-between items-center mb-4">
              <div>
                <h3 className="text-lg font-semibold">GitHub Repository Configuration</h3>
                {isConnected && (
                  <p className="text-sm text-green-600 mt-1">
                    ✓ Connected to {config.repository}
                  </p>
                )}
              </div>
              <button
                onClick={() => setIsOpen(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                ×
              </button>
            </div>

            {isConnected && (
              <div className="bg-blue-50 border border-blue-200 rounded-md p-3 mb-4">
                <h4 className="text-sm font-medium text-blue-900 mb-1">Need to update your token?</h4>
                <p className="text-xs text-blue-700">
                  If you've regenerated your Personal Access Token, update it below and click "Save & Connect" again.
                </p>
              </div>
            )}

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Repository Name
                </label>
                <input
                  type="text"
                  value={config.repository}
                  onChange={(e) => setConfig(prev => ({ ...prev, repository: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="rikisommers/design-tokens"
                />
                <p className="text-gray-500 text-xs mt-1">
                  Enter just the repository name in format: <code className="bg-gray-100 px-1 rounded">username/repository</code><br/>
                  ✅ Correct: "rikisommers/design-tokens"<br/>
                  ❌ Don't include: "https://github.com/..."
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Personal Access Token
                </label>
                <input
                  type="password"
                  value={config.token}
                  onChange={(e) => setConfig(prev => ({ ...prev, token: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="ghp_xxxxxxxxxxxx"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Token needs 'repo' scope permissions
                </p>
              </div>

              {branches.length > 0 && (
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-sm font-medium text-gray-700">
                      Branch
                    </label>
                    <button
                      onClick={() => {
                        setShowCreateBranch(true);
                        setSourceBranch(config.branch);
                      }}
                      className="text-xs text-blue-600 hover:text-blue-700"
                    >
                      + Create Branch
                    </button>
                  </div>
                  <select
                    value={config.branch}
                    onChange={(e) => setConfig(prev => ({ ...prev, branch: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    {branches.map(branch => (
                      <option key={branch} value={branch}>{branch}</option>
                    ))}
                  </select>
                </div>
              )}

              {showCreateBranch && (
                <div className="bg-blue-50 rounded-md p-3 space-y-3">
                  <h4 className="text-sm font-medium text-blue-900">Create New Branch</h4>
                  <div>
                    <label className="block text-xs font-medium text-blue-700 mb-1">
                      Branch Name
                    </label>
                    <input
                      type="text"
                      value={newBranchName}
                      onChange={(e) => setNewBranchName(e.target.value)}
                      placeholder="feature/new-tokens"
                      className="w-full px-2 py-1 text-sm border border-blue-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-blue-700 mb-1">
                      Create From
                    </label>
                    <select
                      value={sourceBranch}
                      onChange={(e) => setSourceBranch(e.target.value)}
                      className="w-full px-2 py-1 text-sm border border-blue-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                    >
                      <option value="">Select source branch</option>
                      {branches.map(branch => (
                        <option key={branch} value={branch}>{branch}</option>
                      ))}
                    </select>
                  </div>
                  <div className="flex justify-end space-x-2">
                    <button
                      onClick={() => {
                        setShowCreateBranch(false);
                        setNewBranchName('');
                        setSourceBranch('');
                      }}
                      className="px-2 py-1 text-xs text-blue-600 hover:text-blue-700"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleCreateBranch}
                      disabled={loading}
                      className="px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
                    >
                      {loading ? 'Creating...' : 'Create'}
                    </button>
                  </div>
                </div>
              )}
            </div>

            <div className="flex justify-between items-center mt-6">
              <div className="flex space-x-3">
                {isConnected && (
                  <>
                    <button
                      onClick={handleDisconnect}
                      className="px-3 py-2 bg-red-100 text-red-700 hover:bg-red-200 rounded-md text-sm font-medium transition-colors"
                      title="Completely disconnect and clear all GitHub settings"
                    >
                      Reset Connection
                    </button>
                  </>
                )}
              </div>
              <div className="space-x-2">
                <button
                  onClick={() => setIsOpen(false)}
                  className="px-4 py-2 text-gray-600 hover:text-gray-700"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSave}
                  disabled={loading}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
                >
                  {loading ? 'Connecting...' : (isConnected ? 'Update & Reconnect' : 'Save & Connect')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// token-manager-stencil/src/components/github-config.disabled/github-config.tsx
import { Component, h, State, Prop, Event, EventEmitter } from '@stencil/core';
import { GitHubService } from '../../services';

interface GitHubRepo {
  repository: string;
  token: string;
  branch: string;
}

@Component({
  tag: 'github-config',
  styleUrl: 'github-config.css',
  shadow: true
})
export class GitHubConfig {
  @Prop() cssClass: string = '';

  @Event() configChange: EventEmitter<GitHubRepo | null>;

  @State() config: GitHubRepo = {
    repository: '',
    token: '',
    branch: 'main'
  };
  @State() isOpen: boolean = false;
  @State() isConnected: boolean = false;
  @State() branches: string[] = [];
  @State() loading: boolean = false;
  @State() showCreateBranch: boolean = false;
  @State() newBranchName: string = '';
  @State() sourceBranch: string = '';

  private githubService = new GitHubService();

  componentWillLoad() {
    this.loadSavedConfig();
  }

  private loadSavedConfig() {
    const saved = localStorage.getItem('github-config');
    if (saved) {
      const savedConfig = JSON.parse(saved);
      this.config = savedConfig;
      this.isConnected = !!(savedConfig.repository && savedConfig.token);
      this.configChange.emit(savedConfig);
    }
  }

  private cleanRepositoryName(repoName: string): string {
    repoName = repoName.trim();

    if (repoName.startsWith('https://github.com/')) {
      repoName = repoName.replace('https://github.com/', '');
    } else if (repoName.startsWith('github.com/')) {
      repoName = repoName.replace('github.com/', '');
    }

    return repoName;
  }

  private validateRepositoryName(repoName: string): boolean {
    return repoName.includes('/') && repoName.split('/').length === 2;
  }

  private handleSave = async () => {
    if (!this.config.repository || !this.config.token) {
      alert('Please enter repository name and GitHub token');
      return;
    }

    const cleanedRepoName = this.cleanRepositoryName(this.config.repository);

    if (!this.validateRepositoryName(cleanedRepoName)) {
      alert('Repository name must be in the format "username/repository-name"\n\nExample: "john/my-tokens" or "company/design-system"');
      return;
    }

    const cleanedConfig = { ...this.config, repository: cleanedRepoName };
    this.config = cleanedConfig;

    this.loading = true;
    try {
      const branchData = await this.githubService.getBranches(this.config.token, cleanedRepoName);
      const branchNames = branchData.map(branch => branch.name);
      this.branches = branchNames;

      if (!branchNames.includes(cleanedConfig.branch)) {
        const defaultBranch = branchNames.includes('main') ? 'main' : branchNames[0] || 'main';
        cleanedConfig.branch = defaultBranch;
        this.config = { ...cleanedConfig, branch: defaultBranch };
      }

      localStorage.setItem('github-config', JSON.stringify(cleanedConfig));
      this.isConnected = true;
      this.isOpen = false;

      this.configChange.emit(cleanedConfig);
    } catch (error) {
      console.error('GitHub connection error:', error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';

      let friendlyMessage = errorMessage;
      if (errorMessage.includes('404') || errorMessage.includes('Not Found')) {
        friendlyMessage = `Repository '${this.config.repository}' not found. Please check the repository name and ensure it exists.`;
      } else if (errorMessage.includes('401') || errorMessage.includes('403')) {
        friendlyMessage = `Access denied to repository '${this.config.repository}'. Please check your token permissions.`;
      } else if (errorMessage.includes('Failed to fetch')) {
        friendlyMessage = `Network error. Please check your internet connection and try again.`;
      }

      alert(`Connection failed: ${friendlyMessage}`);
    } finally {
      this.loading = false;
    }
  }

  private handleDisconnect = () => {
    if (confirm('Are you sure you want to reset your GitHub connection? This will clear all saved settings including your token.')) {
      localStorage.removeItem('github-config');
      this.config = { repository: '', token: '', branch: 'main' };
      this.isConnected = false;
      this.branches = [];
      this.isOpen = false;
      this.configChange.emit(null);
      alert('GitHub connection reset successfully. You can now configure a new connection.');
    }
  }

  private handleCreateBranch = async () => {
    if (!this.newBranchName.trim()) {
      alert('Please enter a branch name');
      return;
    }

    if (!this.sourceBranch) {
      alert('Please select a source branch');
      return;
    }

    this.loading = true;
    try {
      await this.githubService.createBranch(
        this.config.token,
        this.config.repository,
        this.newBranchName.trim(),
        this.sourceBranch
      );

      // Refresh branches list
      const branchData = await this.githubService.getBranches(this.config.token, this.config.repository);
      const branchNames = branchData.map(branch => branch.name);
      this.branches = branchNames;

      // Switch to the new branch
      const updatedConfig = { ...this.config, branch: this.newBranchName.trim() };
      this.config = updatedConfig;
      localStorage.setItem('github-config', JSON.stringify(updatedConfig));
      this.configChange.emit(updatedConfig);

      this.showCreateBranch = false;
      this.newBranchName = '';
      this.sourceBranch = '';
      alert(`Branch '${this.newBranchName.trim()}' created successfully!`);
    } catch (error) {
      alert(`Failed to create branch: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      this.loading = false;
    }
  }

  private handleRepositoryChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    this.config = { ...this.config, repository: target.value };
  }

  private handleTokenChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    this.config = { ...this.config, token: target.value };
  }

  private handleBranchChange = (event: Event) => {
    const target = event.target as HTMLSelectElement;
    this.config = { ...this.config, branch: target.value };
  }

  private handleNewBranchNameChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    this.newBranchName = target.value;
  }

  private handleSourceBranchChange = (event: Event) => {
    const target = event.target as HTMLSelectElement;
    this.sourceBranch = target.value;
  }

  private openConfig = () => {
    this.isOpen = true;
  }

  private closeConfig = () => {
    this.isOpen = false;
  }

  private showCreateBranchForm = () => {
    this.showCreateBranch = true;
    this.sourceBranch = this.config.branch;
  }

  private hideCreateBranchForm = () => {
    this.showCreateBranch = false;
    this.newBranchName = '';
    this.sourceBranch = '';
  }

  render() {
    return (
      <div class={this.cssClass}>
        <div class="config-header">
          <button
            onClick={this.openConfig}
            class={`config-button ${this.isConnected ? 'connected' : 'disconnected'}`}
          >
            {this.isConnected ? (
              <span class="connection-status">
                <span class="status-indicator"></span>
                {this.config.repository} ({this.config.branch})
              </span>
            ) : (
              'Configure GitHub'
            )}
          </button>

          {this.isConnected && (
            <button
              onClick={this.openConfig}
              class="reconfigure-button"
              title="Reconfigure GitHub connection (e.g., update token)"
            >
              Reconfigure
            </button>
          )}
        </div>

        {this.isOpen && (
          <div class="overlay">
            <div class="modal">
              <div class="modal-header">
                <div class="header-content">
                  <h3>GitHub Repository Configuration</h3>
                  {this.isConnected && (
                    <p class="connection-info">
                      ✓ Connected to {this.config.repository}
                    </p>
                  )}
                </div>
                <button class="close-button" onClick={this.closeConfig}>×</button>
              </div>

              {this.isConnected && (
                <div class="info-section">
                  <h4>Need to update your token?</h4>
                  <p>
                    If you've regenerated your Personal Access Token, update it below and click "Save & Connect" again.
                  </p>
                </div>
              )}

              <div class="form-section">
                <div class="form-group">
                  <label>Repository Name</label>
                  <input
                    type="text"
                    value={this.config.repository}
                    onInput={this.handleRepositoryChange}
                    placeholder="rikisommers/design-tokens"
                  />
                  <div class="help-text">
                    Enter just the repository name in format: <code>username/repository</code><br/>
                    ✅ Correct: "rikisommers/design-tokens"<br/>
                    ❌ Don't include: "https://github.com/..."
                  </div>
                </div>

                <div class="form-group">
                  <label>Personal Access Token</label>
                  <input
                    type="password"
                    value={this.config.token}
                    onInput={this.handleTokenChange}
                    placeholder="ghp_xxxxxxxxxxxx"
                  />
                  <div class="help-text">
                    Token needs 'repo' scope permissions
                  </div>
                </div>

                {this.branches.length > 0 && (
                  <div class="form-group">
                    <div class="branch-header">
                      <label>Branch</label>
                      <button
                        type="button"
                        onClick={this.showCreateBranchForm}
                        class="create-branch-button"
                      >
                        + Create Branch
                      </button>
                    </div>
                    <select onInput={this.handleBranchChange}>
                      {this.branches.map(branch => (
                        <option value={branch} selected={this.config.branch === branch}>{branch}</option>
                      ))}
                    </select>
                  </div>
                )}

                {this.showCreateBranch && (
                  <div class="create-branch-section">
                    <h4>Create New Branch</h4>
                    <div class="form-group">
                      <label>Branch Name</label>
                      <input
                        type="text"
                        value={this.newBranchName}
                        onInput={this.handleNewBranchNameChange}
                        placeholder="feature/new-tokens"
                      />
                    </div>
                    <div class="form-group">
                      <label>Create From</label>
                      <select onInput={this.handleSourceBranchChange}>
                        <option value="">Select source branch</option>
                        {this.branches.map(branch => (
                          <option value={branch}>{branch}</option>
                        ))}
                      </select>
                    </div>
                    <div class="create-branch-actions">
                      <button
                        type="button"
                        onClick={this.hideCreateBranchForm}
                        class="button button-secondary"
                      >
                        Cancel
                      </button>
                      <button
                        type="button"
                        onClick={this.handleCreateBranch}
                        disabled={this.loading}
                        class="button button-primary"
                      >
                        {this.loading ? 'Creating...' : 'Create'}
                      </button>
                    </div>
                  </div>
                )}
              </div>

              <div class="modal-footer">
                <div class="footer-left">
                  {this.isConnected && (
                    <button
                      onClick={this.handleDisconnect}
                      class="button button-danger"
                      title="Completely disconnect and clear all GitHub settings"
                    >
                      Reset Connection
                    </button>
                  )}
                </div>
                <div class="footer-right">
                  <button
                    onClick={this.closeConfig}
                    class="button button-secondary"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={this.handleSave}
                    disabled={this.loading}
                    class="button button-primary"
                  >
                    {this.loading ? 'Connecting...' : (this.isConnected ? 'Update & Reconnect' : 'Save & Connect')}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }
}
