// token-manager-stencil/src/components/github-directory-picker.disabled/github-directory-picker.tsx
import { Component, h, State, Prop, Event, EventEmitter } from '@stencil/core';
import { GitHubService } from '../../services';

interface DirectoryItem {
  name: string;
  path: string;
  type: 'dir' | 'file';
  children?: DirectoryItem[];
}

@Component({
  tag: 'github-directory-picker',
  styleUrl: 'github-directory-picker.css',
  shadow: true
})
export class GitHubDirectoryPicker {
  @Prop() githubToken: string;
  @Prop() repository: string;
  @Prop() branch: string;
  @Prop() defaultFilename: string = 'tokens.json';
  @Prop() mode: 'export' | 'import' = 'export';
  @Prop() availableBranches: string[] = [];

  @Event() selectPath: EventEmitter<{ path: string; branch: string }>;
  @Event() cancel: EventEmitter<void>;

  @State() directoryTree: DirectoryItem[] = [];
  @State() expandedDirs: Set<string> = new Set();
  @State() selectedPath: string = '';
  @State() selectedFile: string = '';
  @State() filename: string = this.defaultFilename;
  @State() loading: boolean = true;
  @State() selectedBranch: string = 'main';
  @State() selectionType: 'file' | 'directory' | '' = '';

  private githubService = new GitHubService();

  componentWillLoad() {
    this.filename = this.defaultFilename;
    this.selectedBranch = this.branch;
    this.loadDirectoryContents('');
  }

  componentWillUpdate() {
    if (this.selectedBranch !== this.branch) {
      this.resetState();
      this.loadDirectoryContents('');
    }
  }

  private resetState() {
    this.directoryTree = [];
    this.expandedDirs = new Set();
    this.selectedPath = '';
    this.selectedFile = '';
    this.selectionType = '';
    this.loading = true;
  }

  private async loadDirectoryContents(path: string = '') {
    try {
      const contents = await this.githubService.getDirectoryContents(
        this.githubToken,
        this.repository,
        path,
        this.selectedBranch
      );

      const items = contents
        .filter(item => item.type === 'dir' || item.name.endsWith('.json'))
        .map(item => ({
          name: item.name,
          path: item.path,
          type: item.type as 'dir' | 'file',
          children: item.type === 'dir' ? [] : undefined
        }));

      if (path === '') {
        this.directoryTree = items;
        this.loading = false;
      } else {
        this.directoryTree = this.updateTreeWithContents(this.directoryTree, path, items);
      }
    } catch (error) {
      console.error('Error loading directory:', error);
      alert('Failed to load directory contents');
    }
  }

  private updateTreeWithContents(tree: DirectoryItem[], targetPath: string, newItems: DirectoryItem[]): DirectoryItem[] {
    return tree.map(item => {
      if (item.path === targetPath && item.type === 'dir') {
        return { ...item, children: newItems };
      } else if (item.children && item.path !== targetPath) {
        return { ...item, children: this.updateTreeWithContents(item.children, targetPath, newItems) };
      }
      return item;
    });
  }

  private async toggleDirectory(item: DirectoryItem) {
    if (item.type !== 'dir') return;

    const newExpanded = new Set(this.expandedDirs);

    if (this.expandedDirs.has(item.path)) {
      newExpanded.delete(item.path);
    } else {
      newExpanded.add(item.path);
      if (!item.children || item.children.length === 0) {
        await this.loadDirectoryContents(item.path);
      }
    }

    this.expandedDirs = newExpanded;
  }

  private handleSelect = () => {
    if (this.mode === 'import') {
      if (this.selectionType === 'file' && this.selectedFile) {
        this.selectPath.emit({ path: this.selectedFile, branch: this.selectedBranch });
      } else if (this.selectionType === 'directory') {
        this.selectPath.emit({ path: this.selectedPath, branch: this.selectedBranch });
      } else {
        alert('Please select a JSON file or directory containing tokens');
        return;
      }
    } else {
      if (!this.filename.trim()) {
        alert('Please enter a filename');
        return;
      }

      if (!this.filename.endsWith('.json')) {
        alert('Filename must end with .json');
        return;
      }

      const fullPath = this.selectedPath ? `${this.selectedPath}/${this.filename}` : this.filename;
      this.selectPath.emit({ path: fullPath, branch: this.selectedBranch });
    }
  }

  private handleCancel = () => {
    this.cancel.emit();
  }

  private handleDirectoryClick = (item: DirectoryItem) => {
    if (this.mode === 'import') {
      this.selectedPath = item.path;
      this.selectedFile = '';
      this.selectionType = 'directory';
    } else {
      this.selectedPath = item.path;
    }
    this.toggleDirectory(item);
  }

  private handleFileClick = (item: DirectoryItem) => {
    if (this.mode === 'import') {
      this.selectedFile = item.path;
      this.selectedPath = '';
      this.selectionType = 'file';
    }
  }

  private handleRootClick = () => {
    if (this.mode === 'import') {
      this.selectedPath = '';
      this.selectedFile = '';
      this.selectionType = 'directory';
    } else {
      this.selectedPath = '';
    }
  }

  private handleBranchChange = (event: Event) => {
    const target = event.target as HTMLSelectElement;
    this.selectedBranch = target.value;
  }

  private handleFilenameChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    this.filename = target.value;
  }

  private renderTree(items: DirectoryItem[], level = 0) {
    return items.map(item => (
      <div class="tree-item" style={{ marginLeft: `${level * 20}px` }}>
        {item.type === 'dir' ? (
          <div
            class={`tree-node directory ${this.selectedPath === item.path && this.selectionType === 'directory' ? 'selected-directory' : ''}`}
            onClick={() => this.handleDirectoryClick(item)}
          >
            <span class="icon">📁</span>
            <span class="name">{item.name}</span>
            {this.mode === 'import' && this.selectedPath === item.path && this.selectionType === 'directory' && (
              <span class="selection-indicator directory-selected">Selected</span>
            )}
          </div>
        ) : (
          <div
            class={`tree-node file ${this.selectedFile === item.path ? 'selected-file' : ''}`}
            onClick={() => this.handleFileClick(item)}
          >
            <span class="icon">📄</span>
            <span class="name">{item.name}</span>
            {this.mode === 'import' && this.selectedFile === item.path && (
              <span class="selection-indicator file-selected">Selected</span>
            )}
          </div>
        )}

        {item.children && this.expandedDirs.has(item.path) && (
          <div class="children">
            {this.renderTree(item.children, level + 1)}
          </div>
        )}
      </div>
    ));
  }

  render() {
    if (this.loading) {
      return (
        <div class="overlay">
          <div class="modal loading-modal">
            <div class="loading-content">Loading directory tree...</div>
          </div>
        </div>
      );
    }

    return (
      <div class="overlay">
        <div class="modal">
          <div class="modal-header">
            <h3>{this.mode === 'import' ? 'Select File to Import' : 'Choose Export Destination'}</h3>
            <button class="close-button" onClick={this.handleCancel}>×</button>
          </div>

          <div class="modal-content">
            <div class="directory-section">
              <div class="section-header">
                <div class="section-title">Repository Directory Structure:</div>
                {this.availableBranches.length > 0 && (
                  <div class="branch-selector">
                    <label>Branch:</label>
                    <select onInput={this.handleBranchChange}>
                      {this.availableBranches.map(branchName => (
                        <option value={branchName} selected={this.selectedBranch === branchName}>{branchName}</option>
                      ))}
                    </select>
                  </div>
                )}
              </div>

              <div class="directory-tree">
                <div
                  class={`tree-node root ${this.selectedPath === '' && this.selectionType === 'directory' ? 'selected-directory' : ''}`}
                  onClick={this.handleRootClick}
                >
                  <span class="icon">📁</span>
                  <span class="name">/ (root)</span>
                  {this.mode === 'import' && this.selectedPath === '' && this.selectionType === 'directory' && (
                    <span class="selection-indicator directory-selected">Selected</span>
                  )}
                </div>
                {this.renderTree(this.directoryTree)}
              </div>
            </div>

            {this.mode === 'import' ? (
              <div class="selection-section">
                {this.selectionType === 'file' && this.selectedFile && (
                  <div class="selection-info">
                    <label>Selected File:</label>
                    <div class="selected-path file-path">{this.selectedFile}</div>
                  </div>
                )}
                {this.selectionType === 'directory' && (
                  <div class="selection-info">
                    <label>Selected Directory:</label>
                    <div class="selected-path directory-path">/{this.selectedPath || '(root)'}</div>
                    <p class="info-text">Will import all JSON files from this directory and all subdirectories</p>
                  </div>
                )}
                <div class="status-message">
                  {this.selectionType ? (
                    <span class="ready">✅ Selection ready for import</span>
                  ) : (
                    <span class="instruction">Click on a JSON file or directory above to select it for import</span>
                  )}
                </div>
              </div>
            ) : (
              <div class="export-section">
                <div class="form-group">
                  <label>Selected Directory:</label>
                  <div class="selected-path directory-path">/{this.selectedPath || '(root)'}</div>
                </div>

                <div class="form-group">
                  <label>Filename:</label>
                  <input
                    type="text"
                    value={this.filename}
                    onInput={this.handleFilenameChange}
                    placeholder="tokens.json"
                  />
                </div>

                <div class="form-group">
                  <label>Full Path:</label>
                  <div class="selected-path full-path">
                    {this.selectedPath ? `${this.selectedPath}/${this.filename}` : this.filename}
                  </div>
                </div>
              </div>
            )}
          </div>

          <div class="modal-footer">
            <button class="button button-secondary" onClick={this.handleCancel}>
              Cancel
            </button>
            <button class="button button-primary" onClick={this.handleSelect}>
              Select Path
            </button>
          </div>
        </div>
      </div>
    );
  }
}

// src/components/GitHubDirectoryPicker.tsx
'use client';

import { useState, useEffect } from 'react';

interface DirectoryItem {
  name: string;
  path: string;
  type: 'dir' | 'file';
  children?: DirectoryItem[];
}

interface GitHubDirectoryPickerProps {
  githubToken: string;
  repository: string;
  branch: string;
  onSelect: (path: string, branch: string) => void;
  onCancel: () => void;
  defaultFilename?: string;
  mode?: 'export' | 'import';
  availableBranches?: string[];
}

export function GitHubDirectoryPicker({
  githubToken,
  repository,
  branch,
  onSelect,
  onCancel,
  defaultFilename = 'tokens.json',
  mode = 'export',
  availableBranches = []
}: GitHubDirectoryPickerProps) {
  const [directoryTree, setDirectoryTree] = useState<DirectoryItem[]>([]);
  const [expandedDirs, setExpandedDirs] = useState<Set<string>>(new Set());
  const [selectedPath, setSelectedPath] = useState('');
  const [selectedFile, setSelectedFile] = useState('');
  const [filename, setFilename] = useState(defaultFilename);
  const [loading, setLoading] = useState(true);
  const [selectedBranch, setSelectedBranch] = useState(branch);
  const [selectionType, setSelectionType] = useState<'file' | 'directory' | ''>('');

  // Load directory tree
  useEffect(() => {
    setDirectoryTree([]);
    setExpandedDirs(new Set());
    setSelectedPath('');
    setSelectedFile('');
    setSelectionType('');
    setLoading(true);
    loadDirectoryContents('');
  }, [githubToken, repository, selectedBranch]);

  const loadDirectoryContents = async (path: string = '') => {
    try {
      const apiUrl = `https://api.github.com/repos/${repository}/contents/${path}?ref=${selectedBranch}`;
      const response = await fetch(apiUrl, {
        headers: {
          'Authorization': `token ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      });

      if (!response.ok) {
        throw new Error('Failed to load directory contents');
      }

      const contents = await response.json();

      if (path === '') {
        // Root level
        const items = contents
          .filter((item: any) => item.type === 'dir' || item.name.endsWith('.json'))
          .map((item: any) => ({
            name: item.name,
            path: item.path,
            type: item.type === 'dir' ? 'dir' as const : 'file' as const,
            children: item.type === 'dir' ? [] : undefined
          }));

        setDirectoryTree(items);
        setLoading(false);
      } else {
        // Nested directory - update tree
        const items = contents
          .filter((item: any) => item.type === 'dir' || item.name.endsWith('.json'))
          .map((item: any) => ({
            name: item.name,
            path: item.path,
            type: item.type === 'dir' ? 'dir' as const : 'file' as const,
            children: item.type === 'dir' ? [] : undefined
          }));

        setDirectoryTree(prev => updateTreeWithContents(prev, path, items));
      }
    } catch (error) {
      console.error('Error loading directory:', error);
      alert('Failed to load directory contents');
    }
  };

  const updateTreeWithContents = (tree: DirectoryItem[], targetPath: string, newItems: DirectoryItem[]): DirectoryItem[] => {
    return tree.map(item => {
      if (item.path === targetPath && item.type === 'dir') {
        return { ...item, children: newItems };
      } else if (item.children && item.path !== targetPath) {
        return { ...item, children: updateTreeWithContents(item.children, targetPath, newItems) };
      }
      return item;
    });
  };

  const toggleDirectory = async (item: DirectoryItem) => {
    if (item.type !== 'dir') return;

    const newExpanded = new Set(expandedDirs);

    if (expandedDirs.has(item.path)) {
      newExpanded.delete(item.path);
    } else {
      newExpanded.add(item.path);
      // Load contents if not already loaded
      if (!item.children || item.children.length === 0) {
        await loadDirectoryContents(item.path);
      }
    }

    setExpandedDirs(newExpanded);
  };

  const handleSelect = () => {
    if (mode === 'import') {
      // For import, we can select either a file or directory
      if (selectionType === 'file' && selectedFile) {
        onSelect(selectedFile, selectedBranch);
      } else if (selectionType === 'directory') {
        onSelect(selectedPath, selectedBranch);
      } else {
        alert('Please select a JSON file or directory containing tokens');
        return;
      }
    } else {
      // For export, we need a filename
      if (!filename.trim()) {
        alert('Please enter a filename');
        return;
      }

      if (!filename.endsWith('.json')) {
        alert('Filename must end with .json');
        return;
      }

      const fullPath = selectedPath ? `${selectedPath}/${filename}` : filename;
      onSelect(fullPath, selectedBranch);
    }
  };

  const renderTree = (items: DirectoryItem[], level = 0) => {
    return items.map(item => (
      <div key={item.path} style={{ marginLeft: `${level * 20}px` }}>
        {item.type === 'dir' ? (
          <div
            className={`flex items-center py-1 px-2 rounded cursor-pointer hover:bg-gray-100 ${
              selectedPath === item.path && selectionType === 'directory' ? 'bg-blue-100' : ''
            }`}
            onClick={() => {
              if (mode === 'import') {
                // For import mode, clicking a directory selects it
                setSelectedPath(item.path);
                setSelectedFile('');
                setSelectionType('directory');
              } else {
                // For export mode, clicking a directory just sets it as the parent directory
                setSelectedPath(item.path);
              }
              toggleDirectory(item);
            }}
          >
            <span className="mr-2 text-gray-500">
              {expandedDirs.has(item.path) ? '📁' : '📁'}
            </span>
            <span className="text-sm">{item.name}</span>
            {mode === 'import' && selectedPath === item.path && selectionType === 'directory' && (
              <span className="ml-auto text-xs text-blue-600">Selected</span>
            )}
          </div>
        ) : (
          <div
            className={`flex items-center py-1 px-2 rounded cursor-pointer hover:bg-gray-100 ${
              selectedFile === item.path ? 'bg-green-100' : 'text-gray-600'
            }`}
            onClick={() => {
              if (mode === 'import') {
                setSelectedFile(item.path);
                setSelectedPath('');
                setSelectionType('file');
              }
            }}
          >
            <span className="mr-2">📄</span>
            <span className="text-sm">{item.name}</span>
            {mode === 'import' && selectedFile === item.path && (
              <span className="ml-auto text-xs text-green-600">Selected</span>
            )}
          </div>
        )}

        {item.children && expandedDirs.has(item.path) && (
          <div>
            {renderTree(item.children, level + 1)}
          </div>
        )}
      </div>
    ));
  };

  if (loading) {
    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div className="bg-white rounded-lg p-6 w-96">
          <div className="text-center">Loading directory tree...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] flex flex-col">
        <div className="flex items-center justify-between p-4 border-b">
          <h3 className="text-lg font-medium">
            {mode === 'import' ? 'Select File to Import' : 'Choose Export Destination'}
          </h3>
          <button
            onClick={onCancel}
            className="text-gray-500 hover:text-gray-700"
          >
            ×
          </button>
        </div>

        <div className="flex-1 overflow-auto p-4">
          <div className="mb-4">
            <div className="flex items-center justify-between mb-2">
              <div className="text-sm font-medium text-gray-700">Repository Directory Structure:</div>
              {availableBranches.length > 0 && (
                <div className="flex items-center gap-2">
                  <label className="text-xs font-medium text-gray-700">Branch:</label>
                  <select
                    value={selectedBranch}
                    onChange={(e) => setSelectedBranch(e.target.value)}
                    className="px-2 py-1 text-xs border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    {availableBranches.map(branchName => (
                      <option key={branchName} value={branchName}>{branchName}</option>
                    ))}
                  </select>
                </div>
              )}
            </div>
            <div className="border rounded-md p-3 bg-gray-50 max-h-64 overflow-auto">
              <div
                className={`flex items-center py-1 px-2 rounded cursor-pointer hover:bg-gray-100 ${
                  selectedPath === '' && selectionType === 'directory' ? 'bg-blue-100' : ''
                }`}
                onClick={() => {
                  if (mode === 'import') {
                    setSelectedPath('');
                    setSelectedFile('');
                    setSelectionType('directory');
                  } else {
                    setSelectedPath('');
                  }
                }}
              >
                <span className="mr-2">📁</span>
                <span className="text-sm font-medium">/ (root)</span>
                {mode === 'import' && selectedPath === '' && selectionType === 'directory' && (
                  <span className="ml-auto text-xs text-blue-600">Selected</span>
                )}
              </div>
              {renderTree(directoryTree)}
            </div>
          </div>

          {mode === 'import' ? (
            <div className="space-y-3">
              {selectionType === 'file' && selectedFile && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Selected File:
                  </label>
                  <div className="px-3 py-2 bg-green-50 border border-green-200 rounded text-sm font-mono text-green-800">
                    {selectedFile}
                  </div>
                </div>
              )}
              {selectionType === 'directory' && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Selected Directory:
                  </label>
                  <div className="px-3 py-2 bg-blue-50 border border-blue-200 rounded text-sm font-mono text-blue-800">
                    /{selectedPath || '(root)'}
                  </div>
                  <p className="text-xs text-blue-600 mt-1">
                    Will import all JSON files from this directory and all subdirectories
                  </p>
                </div>
              )}
              <div className="text-sm text-gray-600">
                {selectionType ? (
                  <span>✅ Selection ready for import</span>
                ) : (
                  <span>Click on a JSON file or directory above to select it for import</span>
                )}
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Selected Directory:
                </label>
                <div className="px-3 py-2 bg-gray-50 border rounded text-sm font-mono">
                  /{selectedPath || '(root)'}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Filename:
                </label>
                <input
                  type="text"
                  value={filename}
                  onChange={(e) => setFilename(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="tokens.json"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Full Path:
                </label>
                <div className="px-3 py-2 bg-blue-50 border border-blue-200 rounded text-sm font-mono text-blue-800">
                  {selectedPath ? `${selectedPath}/${filename}` : filename}
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="p-4 border-t flex justify-end space-x-3">
          <button
            onClick={onCancel}
            className="px-4 py-2 text-gray-600 hover:text-gray-700"
          >
            Cancel
          </button>
          <button
            onClick={handleSelect}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
          >
            Select Path
          </button>
        </div>
      </div>
    </div>
  );
}
